ALTER TABLE workstations AUTO_INCREMENT = 1;
INSERT INTO workstations(dept_id, name) VALUES (1, 'OTC');
INSERT INTO workstations(dept_id, name) VALUES (1, 'OTM');
INSERT INTO workstations(dept_id, name) VALUES (1, 'OTB');
INSERT INTO workstations(dept_id, name) VALUES (1, 'PAINTING 1');

INSERT INTO workstations(dept_id, name) VALUES (2, 'FFA');
INSERT INTO workstations(dept_id, name) VALUES (2, 'UBC');
INSERT INTO workstations(dept_id, name) VALUES (2, 'PACK FF');

INSERT INTO workstations(dept_id, name) VALUES (3, 'OCU');
INSERT INTO workstations(dept_id, name) VALUES (3, 'OCC');
INSERT INTO workstations(dept_id, name) VALUES (3, 'PAINTING 3');
INSERT INTO workstations(dept_id, name) VALUES (3, 'PACKING OCU');

INSERT INTO workstations(dept_id, name) VALUES (4, 'PISTON ROD');
INSERT INTO workstations(dept_id, name) VALUES (4, 'CTP');
INSERT INTO workstations(dept_id, name) VALUES (4, 'INNER TUBE');

INSERT INTO workstations(dept_id, name) VALUES (5, 'SA GAS');
INSERT INTO workstations(dept_id, name) VALUES (5, 'SA OLI');
INSERT INTO workstations(dept_id, name) VALUES (5, 'SDA+M');
INSERT INTO workstations(dept_id, name) VALUES (5, 'PAINTING 5');
INSERT INTO workstations(dept_id, name) VALUES (5, 'MOUNTING SA');
INSERT INTO workstations(dept_id, name) VALUES (5, 'MOUNTING SA 3');
INSERT INTO workstations(dept_id, name) VALUES (5, 'PACKAGING SA');
INSERT INTO workstations(dept_id, name) VALUES (5, 'SUPPORT SA');

ALTER TABLE sub_workstations AUTO_INCREMENT = 1;
INSERT INTO sub_workstations(workstation_id, name) VALUES (1, 'OTC');
INSERT INTO sub_workstations(workstation_id, name) VALUES (2, 'OTM');
INSERT INTO sub_workstations(workstation_id, name) VALUES (3, 'OTB');
INSERT INTO sub_workstations(workstation_id, name) VALUES (4, 'PAINTING 1');

INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'FFA 1');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'FFA 2');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'FFA 3');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'FFA 4');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'FFA 5');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'SUPPORT');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'OTHER');
INSERT INTO sub_workstations(workstation_id, name) VALUES (5, 'REPAIR');
INSERT INTO sub_workstations(workstation_id, name) VALUES (6, 'UBC');
INSERT INTO sub_workstations(workstation_id, name) VALUES (7, 'PACK FF');

INSERT INTO sub_workstations(workstation_id, name) VALUES (8, 'OCU 2');
INSERT INTO sub_workstations(workstation_id, name) VALUES (8, 'OCU 3');
INSERT INTO sub_workstations(workstation_id, name) VALUES (8, 'OCU 4');
INSERT INTO sub_workstations(workstation_id, name) VALUES (8, 'OCU 5');
INSERT INTO sub_workstations(workstation_id, name) VALUES (8, 'OCU 5 BARU');
INSERT INTO sub_workstations(workstation_id, name) VALUES (8, 'SUPPORT');
INSERT INTO sub_workstations(workstation_id, name) VALUES (9, 'OCC');
INSERT INTO sub_workstations(workstation_id, name) VALUES (10, 'PAINTING 3');
INSERT INTO sub_workstations(workstation_id, name) VALUES (11, 'PACKING OCU');

INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'PRM');
INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'PRG');
INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'PRH');
INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'PRP');
INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'PRB');
INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'INSPECTOR BUFFING');
INSERT INTO sub_workstations(workstation_id, name) VALUES (12, 'WWT');
INSERT INTO sub_workstations(workstation_id, name) VALUES (13, 'CTP');
INSERT INTO sub_workstations(workstation_id, name) VALUES (14, 'ITG');
INSERT INTO sub_workstations(workstation_id, name) VALUES (14, 'ITP + ITO');
INSERT INTO sub_workstations(workstation_id, name) VALUES (14, 'INPECTOR ITO');

INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'SA1');
INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'SA3');
INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'SA6');
INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'SA7');
INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'SA8');
INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'SA9');
INSERT INTO sub_workstations(workstation_id, name) VALUES (15, 'QA GATE');
INSERT INTO sub_workstations(workstation_id, name) VALUES (16, 'SA 2');
INSERT INTO sub_workstations(workstation_id, name) VALUES (16, 'SA 4');
INSERT INTO sub_workstations(workstation_id, name) VALUES (16, 'SA 5');
INSERT INTO sub_workstations(workstation_id, name) VALUES (17, 'SDA+M');
INSERT INTO sub_workstations(workstation_id, name) VALUES (18, 'PAINTING 5');
INSERT INTO sub_workstations(workstation_id, name) VALUES (19, 'MOUNTING SA');
INSERT INTO sub_workstations(workstation_id, name) VALUES (20, 'MOUNTING SA 3');
INSERT INTO sub_workstations(workstation_id, name) VALUES (21, 'PACKAGING SA');
INSERT INTO sub_workstations(workstation_id, name) VALUES (22, 'SAS');
INSERT INTO sub_workstations(workstation_id, name) VALUES (22, 'CLEANING CENTER');
INSERT INTO sub_workstations(workstation_id, name) VALUES (22, 'OSC 1');
INSERT INTO sub_workstations(workstation_id, name) VALUES (22, 'OSC 2');
INSERT INTO sub_workstations(workstation_id, name) VALUES (22, 'WLC');
INSERT INTO sub_workstations(workstation_id, name) VALUES (22, 'INSPECTOR SUPPORT');

-- INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), '');
ALTER TABLE process AUTO_INCREMENT = 1;
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'CHARGING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'TREATMENT CAIRAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'POURING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'GRAVITY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'CUTTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'SANDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'GANTI MODEL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'SUPLYMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'WELDING BAND SAW');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'REPAIR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'ALFA ROBOT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'CAROUSEL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'PREDRILL/MACOD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'GANTRY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'QUALITY GATE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'MAINTENANCE DIES');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'MAINTENANCE CORE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'CONTROLMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'YUNGSAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'SMELTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'AUTO CUTTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTC'), 'MAPI');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'ROBO DRILL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'MANUAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'TAKISAWA');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'MORISEIKI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'SUPPLY OTC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'SUPPLY OTB');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'ROBOT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'OLI / COOLANT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'BTA');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'CEK DIMENSI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'PICKINGMAN LIBERO');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'PREP TOOL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'CONTROLMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'SOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'PEMAHAMAN PRODUCT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'PEMAHAMAN PART "OK" & "NG"');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'PROBLEM SOLVING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'CHECK VISUAL O/TUBE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'QUALITY AWARENESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTM'), 'CEK DIMENSI');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'BUFFING MOPED');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'BUFFING SPORT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'REPAIR BUFFING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'KEROK ROLL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'BUAT ROLL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'REPAIR PAINTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'REPAIR BELTON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'AIR BLOW');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'THICKNESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'QUALITY GATE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTB'), 'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'LOADING ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'MASKING & SET POSISI O.TUBE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'SETTING ROBOT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'TOUCH UP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'MIXING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'TITRASI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'UNLOADING/LEPAS MASKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'PICKMAN ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'AEROX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'REPAIR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'TARIK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'THICKNESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'POLESHING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'LINE KEEPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'LG BOARD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'SOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'PEMAHAMAN PRODUCT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'PEMAHAMAN PART "OK" & "NG"');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'PROBLEM SOLVING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'QUALITY AWARENESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'PDI FF ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'INSPECTOR FF ASY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 1'), 'CHECK VISUAL O/TUBE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'INSERTING CYLINDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'I/TUBE CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'ASSY DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'NUT RUNNER & OIL SEAL PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'PRESS DUST SEAL & CEK UNSMOOTH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'LEAKAGE TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'OIL FILLING & INSERT SPRING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'C-PIN 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'PRESS PROTECTOR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'INSERTING DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'BOLT TIGHT UBC & CHECK AXLE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'CEK TORQUE & MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'DAMPING FORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'ASSY CYL COMP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'REPACK.O/SEAL, BOLT & ASSY BOLT+PACK DLL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'PRESS BALL RACE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 1'), 'PICKINGMAN');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'INSERTING PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'INSERTING CYLINDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'I/TUBE CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'ASSY DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'NUT RUNNER O/SEAL PRES');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'SNAP RING SEAT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'PRESS DUST SEAL & UNSMOOTH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'LEAKAGE TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'INSERTING DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'TIGHT. BOLT UBC & TENSION');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'CHECK 3 POINT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'INSERT OIL & SPRING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'CAP TIGHTENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'CHECK HUB LENGHT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'DAMFING FORCE MANUAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'PRESS UBC COMPLETE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 2'),'ASSY CYL COMP');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'INSERTING PART, CYLINDER & CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'I/TUBE CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'NUT RUNNER DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'OIL SEAL PRESS, SNAP RING SEAT & PRESS DUST SEAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'PRESS DUST SEAL & UNSMOOTH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'LEAKAGE TESTER & OIL FILLING INSERT SPRING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'C-PIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'INSERTING DAMPER, BOLT TIGHT UBC & CHECK AXLE ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'BOLT TIGHTENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'CONFIRM TORQUE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'CONFIRM TORQUE & MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'DAMPING FORCE MANUAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'ASSY CYL COMP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'REPACK.O/SEAL &BOLT + ASSY BOLT+PACK DLL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 3'),'PRESS BALL RACE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'AX.BRACKET/SCREW TIGHT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'BOLT TIGHTNING/OIL SEAL GRS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'PRESS OILSEAL/DUST SEAL/SNAPRING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'OIL FILLING/TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'DAMPING FORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'CAP TIGTHENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'ASSY DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'3 POINT/PRESS BALLRACE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'PICKMAN + AXLE LINE 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'CLEANING/ PICKINGMAN L4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'SUB ASSY CYL COM');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'REPACK.O/SEAL, BOLT & ASSY BOLT+PACK DLL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 4'),'CLEANING INERTUBE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'INSERTING PART, CYLINDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'I/TUBE CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'NUT RUNNER DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'OIL SEAL PRESS, SNAP RING SEAL ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'PRESS DUST SEAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'LEAKAGE TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'OIL FILLING INSERT SPRING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'C-PIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'DAMPING FORCE MESIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'DAMPING FORCE MANUAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'SUB ASSY CYL COMP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'REPACK.O/SEAL &BOLT + ASSY BOLT+PACK DLL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'FFA 5'),'PICKINGMAN');

INSERT INTO process(workstation_id, name) VALUES (10,'CLEANING SPRING');
INSERT INTO process(workstation_id, name) VALUES (10,'P / M TPOP ( CKD )');
INSERT INTO process(workstation_id, name) VALUES (10,'PICKINGMAN PALLET/UBC');
INSERT INTO process(workstation_id, name) VALUES (10,'CLEANING CYLINDER');
INSERT INTO process(workstation_id, name) VALUES (10,'CLEANING INNER TUBE');
INSERT INTO process(workstation_id, name) VALUES (10,'SUPPLY');
INSERT INTO process(workstation_id, name) VALUES (10,'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'PASANG UPB XD 831 / BEARING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'SIKAT ST.SHAFT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'CLEANING BOX /  TRAY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'IMPROVE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'LINE GUIDE IMPROVEMENT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'REAPAIR MOPED');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'REPAIR SPORT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'REPAIR UP SIDE DOWN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'BONGKAR PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'TRANSAKSI BAAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OTHER'),'ASSY POD');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'IDENTIFIKASI DEFFECT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'LEPAS  DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'LEPAS C PIN /CAP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'BONGKAR DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'IDENTIFIKASI PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'MERAPIKAN PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'RUSAK  PART NG');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'BUANG  LIMBAH EX REPAIR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'REPAIR'),'TRANSACTION CONTROL');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'PRESS & WELDING 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'PRESS & WELDING 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'PRESS & WELDING 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'PRESS & WELDING 5 /7');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'PRESS & WELDING 8');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'INSPECTOR UBC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'POLESH UBC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'SUPPLY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'LINE GUIDE UBC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'IMPROVEMENT + 5R + PICK UP DEFECT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'REPAIR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'UBC'),'LG BOARD');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'PREPARATION BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'WEIGHTING PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'LABELING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'SET IN PALLET/BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'FORKLIFT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'PACK POD GP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'IT CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'PRESS BALLRACE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'PRESS OUTERTUBE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'TRANSAKSI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACK FF'),'PACK EXPORT');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'SUB ASSY PISTON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'SUB ASSY PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'HI SPIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'ROLLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'OIL FILLING ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'MARKING LASER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'MOUNTING PARTS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'SPRING PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'FREE LENGTH CHECK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'STROKE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'SUPPLY PARTS CKD / TPOP LINE 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'LINE GUIDE SPRING PRESS LINE 1 + 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'CLEANING S PART / HIDRO CARBONE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'CLEANING PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'TOWING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'SEAL PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 2'),'UCEK UCEK + VACUM');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'SUB ASSY PISTON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'SUB ASSY PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'HISPIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'OIL FILLING ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'ROLLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),' STROKE ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'MARKING LASER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'MOUNTING PARTS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'SPRING PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'FREE LENGTH CHECK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'SUPPLY PARTS CKD / TPOP LINE 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'SUPPORT LINE 3 ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'OIL SEAL PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'CAULKING DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'CAULK KIWA');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'CLEANING JKS ( CYL COMP )');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 3'),'TRANFER CYLINDER');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'SUPPORTING DAMPER ASSY ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'SUB ASSY PISTON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'TIGHTENING CAULKING ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'OIL SEAL PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'D/F TESTER ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'MOUNTING PARTS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'SPRING PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'FREE LENGTH CHECK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'PRESS RB.BUSHING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'SUPPLY PARTS CKD / TPOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'SUPPORT LINE 4 + BANTU FREE LENGHT + WD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'BVC ASSY ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'LINE GUIDE SPRING PRESS LINE 3 + 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'LINE GUIDE CLOSE ROOM LINE 3 + 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'CLEANING JKS ( CYL COMP )');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'CLEANING WATER FALL ( O SHELL + CYL ISI )');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'TRANSFER CYL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'HI-SPIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'PRESS CYLINDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 4'),'CONDENSOR WELDING');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'MOUNTING PARTS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'MARKING LASER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'SPRING PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'FREE LENGTH CHECK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'SUPPLY PARTS CKD / TPOP LINE 5');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'BONGKAR DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'SUB ASSY ORING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'SUB ASSY PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'HISPIN ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'CAULKING ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'TIGHTENING TANK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'PRESS BLADDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'SUPPORT DAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'PRESS CAP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'OIL SEAL PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'ROLLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'LEAKAGE TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'PDI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'SUB ASSY PISTON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'SUB ASSY PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'HI SPIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'ROLLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'OIL FILLING ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'SLITING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'TIGHTENING TANK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'PRESS BLADDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'LEAKAGE TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'SUPPLY PARTS CKD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'LINE GUIDE ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'MARKING LASER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'MOUNTING PARTS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCU 5 BARU'),'SPRING PRESS');

INSERT INTO process(workstation_id, name) VALUES (20,'CLEANING SMALL PART / HIDRO CARBONE');
INSERT INTO process(workstation_id, name) VALUES (20,'CLEANING PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES (20,'CLEANING PISTON ROD WELDING');
INSERT INTO process(workstation_id, name) VALUES (20,'TOWING');
INSERT INTO process(workstation_id, name) VALUES (20,'REJECT (ANALISA/INPUT BONGKAR MOUNTING)');
INSERT INTO process(workstation_id, name) VALUES (20,'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES (20,'LINE KEEPER');
INSERT INTO process(workstation_id, name) VALUES (20,'IMPROVEMENT');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'REINFORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'P.ROD WELD.');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'ROTARY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'SEAM WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'STOPPER WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'EYE CAP WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'GRINDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'SPOT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'PROJ. WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'COND. WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'CHAMPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'ROBOT REINFORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'BUFFING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'BRUSH CYLINDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OCC'),'GENJOT OCU');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'SETTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'TOUCH UP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'MIXING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'TITRASI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'INSPECTOR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'LOADING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'UN LOADING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'REPAIR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'MASKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'TARIK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 3'),'PRESS BHUSING');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'PREPARATION BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'INSERT TO THE BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'WEIGHTING PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'LABELING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'SET IN PALLET/BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'PACKAGING GP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'PIC KONTROL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKING OCU'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'SUPPLYMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'MIYANO');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'CUTTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'ROLLING M12-M14');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'ROLLING M6,M7,M8 & M10');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'KIT / STOREMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'MILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'HEXAGON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'BORRING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRM'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PRG 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PRG 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PRG 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PRG 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PRG 5');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PRG 6');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRG'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRH'),'HARDENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRH'),'TEMPERING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRH'),'CUTTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRH'),'HRA CHECK');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'PRP 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'PRP 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'PRP 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'PRP 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'STOREMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'RA & BLAKEN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRP'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 5');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 6');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PRB'),'PRB 7');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'SOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'INSPECTION REPORT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'"S" PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'PEMAHAMAN PRODUCT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'PEMAHAMAN PART "OK" & "NG"');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'PROBLEM SOLVING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR BUFFING'),'QUALITY AWARENESS');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WWT'),'PAINTING PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WWT'),'CHROME PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WWT'),'NICKEL PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WWT'),'FILTER PRESS');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'REDUCING + EXPAND');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'BEAD CRUSHER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'REJECT ANALYSE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'SUPPLYMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'SOTERMAN KIT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CTP'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'ITG 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'ITG 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'ITG 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'ITG 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'ITG 5');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'ITG 6');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'INSPECTION');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'CHECK COOLANT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITG'),'IMPROVEMENT');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITP 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITP 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITP 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITO 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITO 2');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITO 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITO 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'ITP 4');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'STOCK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'CHECK CHEMICAL NICKEL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'ITP + ITO'),'CEK THICKNESS');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'SOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'INSPECTION REPORT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'PATROL SYSTEM');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'"S" PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'SPC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'PEMAHAMAN PRODUCT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'PEMAHAMAN PART "OK" & "NG"');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'PROBLEM SOLVING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'QUALITY AWARENESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INPECTOR ITO'),'CHECK VISUAL I/TUBE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'PAINTING MINI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'LOWER CAP PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'LOWER SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'CLEANING O/S');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'TABLE ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'CRIMPING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'AUTOTIGH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'BVC PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'CLEANING PISTONROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'PACKINGCASE PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'UPPERSEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'ROLLCLOSSING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'INSERT PLUG');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'GAS OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'AIR REMAINING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'LOWER PROJECTION');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'REINFORCE WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'COVER PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'SPOT WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'RB PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'SENSOR BRACKET');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA1'),'HOSE BRACKET');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'TOWING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'PRE CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'O/SHELL CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'PISTON ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'AUTOTIGH & CAULCKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'BVC PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'PACKING CASE PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'UPPERSEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'GAS FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'ROLL CLOSSING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA3'),'BUMP STOPPER');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'PAINTING MINI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'LOWER CAP PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'LOWER SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'O/SHELL CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'TABLE ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'TIGHTENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'P/ROD CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'AUTO BVC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'ROLL CLOSSING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'INSERT PLUG');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'GAS OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'AIR REMAINING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'LOWER PROJECTION WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'COVER PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'REINFORCE WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'SPOT COVER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA6'),'RUBBER PRESS');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'LOWER CAP PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'LOWER SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'CLEANING O/S');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'PISTON ASSY COMPLETE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'AUTOTIGH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'BVC PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'CLEANING PISTON ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'PACKING CASE PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'UPPER SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'ROLLCLOSSING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'INSERT PLUG');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'GAS OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'AIR REMAINING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'LOWER PROJECTION');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'REINFORCE WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'COVER PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'SPOT WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'RB PRESS UPPER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'RB PRESS LOWER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'SENSOR BRACKET');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA7'),'HOSE BRACKET');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'O/SHELL CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'TABLE ASSY & AUTOTIGHTENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'GAS FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'ROLL CLOSING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA8'),'BUMP STOPPER');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'O/SHELL MARKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'REDUCHING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'SPRING SEAT WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'P/ROD WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'CLEANING P/ROD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'LOWER CAP PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'LOWER SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'CLEANING PARTS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'TABLE ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'CRIMPING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'TIGHTENING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'HI SPIN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'CLEANING P/ROD COMPLETE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'AUTO BVC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'ROLL CLOSSING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'INSERT PLUG');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'GAS OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'ASSY BVC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'ASSY PISTON');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'AIR REMAINING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'PAINTING MINI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'LOWER PROJECTION WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'LOWER PROJECTION BOSS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'ROTARY WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'COVER PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'SPOT COVER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'REINFORCE WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'SENSOR BRACKET');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA9'),'HOSE BRACKET');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'SOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'INSPECTION REPORT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'"S" PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'PEMAHAMAN PRODUCT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'PEMAHAMAN PART "OK" & "NG"');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'QUALITY AWARENESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'QA GATE'),'CHECK FUNCTION');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'LOWER SEAM WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'TIGHTENING CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'P. R. ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'UPP SEAM WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'SPOT WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'RB PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'LINE GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'PISTON PARTS ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 2'),'BVC PARTS ASSY');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'RB. BUSH PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'P/ROD CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'OIL FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'LOW SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'UPPER SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'PISTON ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'CLEANING MANUAL');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'SUPPLY LOWER SEAM ');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'X PIN PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'SPOT WELD COVER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'PISTON PARTS ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'BVC PARTS ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 4'),'PULL/PUSH DAMPER');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 5'),'D/F TESTER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 5'),'PISTON ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SA 5'),'TIGHT CAULKING');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'LOW SEAM WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'ROLLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'P/R ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'GAS FILLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'PROJ WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'CAULKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'PUNCHING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'FINAL INSPECTION');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SDA+M'),'BRACKET ASSY FINISH GOOD');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'SETTING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'TOUCH UP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'MIXING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'TITRASI');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'INSPECTOR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'LOADING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'UN LOADING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'REPAIR');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'MASKING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'TARIK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'PULLING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PAINTING 5'),'POLESH');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'ASSY BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING SA 9');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING SA 7');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING SA 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING SA 6');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING SA 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING 8 (BSP F)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNTING 9 (IMV F)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNT TRANSFER AM/OEM');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNT 11 (PACK TYT EKSPOR)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNT 13 (HPM REAR)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNT 14 (HPM FRONT ASSY PART)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA'),'MOUNT 14 (HPM FRONT SPRING PRESS)');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'ASSY BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING SA 9');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING SA 7');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING SA 1');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING SA 6');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING SA 3');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING 8 (BSP F)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNTING 9 (IMV F)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNT TRANSFER AM/OEM');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNT 11 (PACK TYT EKSPOR)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNT 13 (HPM REAR)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNT 14 (HPM FRONT ASSY PART)');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'MOUNTING SA 3'),'MOUNT 14 (HPM FRONT SPRING PRESS)');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'SUPPLY / SHOPING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'PREPARATION BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'INSERT TO THE BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'WEIGHTING PART');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'LABELING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'SET IN PALLET/BOX');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'PACKAGING SA'),'FORKLIFT');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'PISTON SLITING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'BVC SLITING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'PISTON PARTS ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'BVC PARTS ASSY');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'OIL SEAL PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'OIL SEAL GREASING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'PARTS CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'RACIK');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'PISTON MOULD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'CRIMPING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'BVC AUTO');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'BLOW ROD GUIDE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'SAS'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CLEANING CENTER'),'PART CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CLEANING CENTER'),'CLEANING CYLINDER');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CLEANING CENTER'),'P/ROD CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CLEANING CENTER'),'O/S CLEANING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'CLEANING CENTER'),'PICKINGMAN');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'LOWER CAP PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'LOWER CAP WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'UPPER WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'SPRING SEAT WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'PREHEATING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'SENSOR WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'BRACKET PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'HOSE BRACKET WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'DOUBLE TORCH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'KNUCKLE REFORMING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'KNUCKLE PUNCHING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'ROBO WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 1'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'LOWER CAP PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'LOWER CAP WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'UPPER WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'SPRING SEAT WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'PREHEATING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'SENSOR WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'BRACKET PRESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'HOSE BRACKET WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'DOUBLE TORCH');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'KNUCKLE REFORMING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'KNUCKLE PUNCHING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'ROBO WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'OSC 2'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'UPPER PROJECT WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'LOWER PROJECTION');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'DOUBLE SPOT REINFORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'SINGLE SPOT REINFORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'ROTARY SUV F WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'SPRIN SEAT IMV-F WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'COVER SPOT WELD');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'P/ROD SPOT WELDING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'STRAIGHT REINFORCE');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'PICKINGMAN');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'WLC'),'LINE GUIDE');

INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'SOP');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'INSPECTION REPORT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'PATROL SYSTEM');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'"S" PROCESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'SPC');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'PEMAHAMAN PRODUCT');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'PEMAHAMAN PART "OK" & "NG"');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'PROBLEM SOLVING');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'QUALITY AWARENESS');
INSERT INTO process(workstation_id, name) VALUES ((SELECT id FROM sub_workstations WHERE name = 'INSPECTOR SUPPORT'),'CHECK FUNCTION ');
